### PR TITLE
#72 - tests admin.views.py

### PR DESCRIPTION
**Pull request by jfunez**
novos tests com covertura de 72%

- test_access_to_admin_index_must_redirect_to_login_form
- test_admin_index_content_counts_is_ok
- test_confirm_email_with_invalid_token_raise_404_message
- test_confirmation_email_send_email_with_token
- test_create_user_from_admin_page_creates_a_new_user
- test_email_confimation_token_of_invalid_user_raise_404_error_message
- test_invalid_credentials_login_must_show_validation_error
- test_invalid_password_login_must_show_validation_error
- test_invalid_user_login_must_show_validation_error
- test_link_sent_via_email_to_reset_password_works_fine
- test_login_page_must_have_link_to_password_reset
- test_login_page_must_have_set_language_links
- test_login_successfully
- test_login_valid_user_with_invalid_password_raise_error_msg
- test_login_with_unconfirmed_user_must_not_proceed
- test_logout_successfully
- test_open_confirm_url_with_token_sent_via_email_open_the_correct_page
- test_reset_password_has_form_as_expected
- test_reset_password_of_invalid_user_raise_404
- test_reset_password_of_valid_user_email_sent
- test_reset_password_of_valid_user_proceed_ok
- test_reset_password_send_valid_link_via_email
- test_reset_password_with_invalid_password_raise_validation_error
- test_reset_password_with_invalid_token_raise_404_error_page
- test_reset_password_with_unconfirmed_email_raise_validation_error_2
- test_reset_password_with_unconfirmed_email_shows_unconfirm_email_error
- test_try_to_create_user_without_email_must_raise_error_notification
- test_unauthorized_access_to_admin_index_must_redirect
- test_admin_article_action_publishing_a_public_article
- test_admin_article_action_publishing_an_unpublished_article
- test_admin_article_action_unpublish_by_abuse_a_public_article
- test_admin_article_action_unpublish_by_copyright_a_public_article
- test_admin_article_action_unpublish_plagiarism_a_public_article
- test_admin_article_check_actions_defined
- test_admin_article_check_can_create_is_false
- test_admin_article_check_can_delete_is_false
- test_admin_article_check_can_edit_is_false
- test_admin_article_check_can_view_details_is_true
- test_admin_article_check_column_exclude_list
- test_admin_article_check_column_filters
- test_admin_article_check_column_formatters
- test_admin_article_check_column_labels_defined
- test_admin_article_check_create_modal_is_true
- test_admin_article_check_edit_modal_is_true
- test_admin_article_check_searchable_columns
- test_admin_article_details
- test_admin_article_list_records
- test_admin_article_search_by_id
- test_admin_issue_action_publishing_a_public_issue
- test_admin_issue_action_publishing_an_unpublished_issue
- test_admin_issue_action_unpublish_by_abuse_a_public_issue
- test_admin_issue_action_unpublish_by_copyright_a_public_issue
- test_admin_issue_action_unpublish_plagiarism_a_public_issue
- test_admin_issue_check_actions_defined
- test_admin_issue_check_can_create_is_false
- test_admin_issue_check_can_delete_is_false
- test_admin_issue_check_can_edit_is_false
- test_admin_issue_check_can_view_details_is_true
- test_admin_issue_check_column_exclude_list
- test_admin_issue_check_column_filters
- test_admin_issue_check_column_formatters
- test_admin_issue_check_column_labels_defined
- test_admin_issue_check_create_modal_is_true
- test_admin_issue_check_edit_modal_is_true
- test_admin_issue_check_searchable_columns
- test_admin_issue_details
- test_admin_issue_list_records
- test_admin_issue_search_by_id
- test_admin_journal_action_publishing_a_public_journal
- test_admin_journal_action_publishing_an_unpublished_journal
- test_admin_journal_action_unpublish_by_abuse_a_public_journal
- test_admin_journal_action_unpublish_by_copyright_a_public_journal
- test_admin_journal_action_unpublish_plagiarism_a_public_journal
- test_admin_journal_check_actions_defined
- test_admin_journal_check_can_create_is_false
- test_admin_journal_check_can_delete_is_false
- test_admin_journal_check_can_edit_is_false
- test_admin_journal_check_can_view_details_is_true
- test_admin_journal_check_column_exclude_list
- test_admin_journal_check_column_filters
- test_admin_journal_check_column_formatters
- test_admin_journal_check_column_labels_defined
- test_admin_journal_check_create_modal_is_true
- test_admin_journal_check_edit_modal_is_true
- test_admin_journal_check_searchable_columns
- test_admin_journal_details
- test_admin_journal_list_records
- test_admin_journal_search_by_id

adicionados 21/Fev

- test_admin_journal_action_publish_with_exception_raised_must_be_consistent
- test_admin_journal_action_unpublish_for_plagiarism_with_exception_raised_must_be_consistent
- test_admin_issue_action_publish_with_exception_raised_must_be_consistent
- test_admin_issue_action_unpublish_for_plagiarism_with_exception_raised_must_be_consistent
- test_admin_article_action_publish_with_exception_raised_must_be_consistent
- test_admin_article_action_unpublish_for_plagiarism_with_exception_raised_must_be_consistent
- test_admin_collection_list_records
- test_admin_collection_details
- test_admin_collection_check_column_exclude_list
- test_admin_collection_check_form_excluded_columns
- test_admin_collection_check_can_create_is_false
- test_admin_collection_check_can_edit_is_true
- test_admin_collection_check_can_delete_is_false
- test_admin_collection_check_create_modal_is_true
- test_admin_collection_check_edit_modal_is_true
- test_admin_collection_check_can_view_details_is_true
- test_admin_sponsor_list_records
- test_admin_sponsor_details
- test_admin_sponsor_check_column_exclude_list
- test_admin_sponsor_check_form_excluded_columns
- test_admin_sponsor_check_can_create_is_true
- test_admin_sponsor_check_can_edit_is_true
- test_admin_sponsor_check_can_delete_is_true
- test_admin_sponsor_check_create_modal_is_true
- test_admin_sponsor_check_edit_modal_is_true
- test_admin_sponsor_check_can_view_details_is_true
- test_admin_sponsor_check_searchable_columns

bon apetite! :P

### CODE REVIEW

**Comment by jfunez** [comment]
@jamilatta ainda temos que discutir o que foi conversado pelo IRC. por isso a marca de "[impedido]"

**Comment by jfunez** [comment]
e muito provável que da conflito de merge com os outros PRs que mudaram o ``test/utils.py``

**Comment by jamilatta** [comment]
Ciente.

2016-02-17 18:13 GMT-02:00 Juan Funez <notifications@github.com>:

> e muito provável que da conflito de merge com os outros PRs que mudaram o
> test/utils.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/opac/pull/90#issuecomment-185382512>.
>



-- 

Jamil Atta Junior

**Comment by jfunez** [comment]
@jamilatta já atualizei e agora temos 115 tests no admin views e cobertura de 84% :beers:

**Comment by jamilatta** [comment]
Boa!

**Pull request merged**
