### PR TITLE
Add Issue filters by journal, volume, number, type, start_month, end_…

### LINKED ISSUE #30: Revisar as filtragens por fascículos
## Problema:

Os campos de filtragem para os fascículos estão incompletos

## Objetivo: 

1. Revisar os campos de filtragem disponíveis para os fascículos na interface de administração, pelo seguintes campos:

* Periódico
* Licença de uso
* Volume
* Número
* Tipo
* Mês de inicio
* Mês de final
* Ano
* Publicado/Despublicado

#### Atores:
- usuário administrador (webmaster)

#### Fluxo de Eventos Primário (caminho básico):

1. O caso de uso começa quando o usuário administrador acessa a listagem de fascículos no admin. 
2. O usuário utiliza os filtros, aplicado para cada um dos campos mencionados acima.
3. O Sistema mostra a listagem filtrada pelos critérios da busca.

#### Fluxo de Secundário (caminho alternativo):
*Não corresponde.*

#### Pré-condição:
- O usuário administrador tem acesso ao admin.
- Tem fascículos suficientes para aplicar as pesquisas.

##### Pós-condição:
- Nenhum fascículo deve ser modificado.

### PR DESCRIPTION
**Pull request by swarzesherz**
…month, year, is_public
Fix #30

### CODE REVIEW

**Comment by swarzesherz** [comment]
Es preferible resolver primero #29

**Comment by jfunez** [comment]
:+1:  estoy revisando!

**Comment by jfunez** [comment]
Aguardando a resolução dos conflitos :zap:

**Comment by swarzesherz** [comment]
Actualizado con la resolución de conflictos

**Comment by jfunez** [comment]
:+1:  revisando!

**Comment by jfunez** [comment]
incorporado em https://github.com/scieloorg/opac/commit/c0ec248ab0b16b4d0051ef08eb7314b84b6c9da2  :beers:

**Pull request merged**
